/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package xyz.techtwins.kafka.demo;
@org.apache.avro.specific.AvroGenerated
public enum Status implements org.apache.avro.generic.GenericEnumSymbol<Status> {
  PENDING, APPROVED, DECLINED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Status\",\"namespace\":\"xyz.techtwins.kafka.demo\",\"symbols\":[\"PENDING\",\"APPROVED\",\"DECLINED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
